export interface Dhikr {
  arabic: string;
  transliteration: string;
  translation: string;
  reference: string;
  count: number;
  title: string;
}

export const ADHKAR_CONTENT: Record<string, Dhikr[]> = {
  morning: [
    {
      title: 'Opening of the morning',
      arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
      transliteration: "Asbahna wa asbahal-mulku lillah, la ilaha illallahu wahdahu la shareeka lah",
      translation: "We have reached the morning and the dominion belongs to Allah. Praise is for Allah. There is no deity except Allah alone, without partner.",
      reference: 'Sahih Muslim 2723',
      count: 1,
    },
    {
      title: 'Morning remembrance',
      arabic: 'اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ',
      transliteration: "Allahumma bika asbahna wa bika amsayna, wa bika nahya wa bika namutu wa ilaykan-nushur",
      translation: "O Allah, by You we enter the morning and by You we enter the evening; by You we live and by You we die, and to You is the resurrection.",
      reference: 'Abu Dawud 5068; Tirmidhi 3391',
      count: 1,
    },
    {
      title: 'Witnessing Allah',
      arabic: 'اللَّهُمَّ إِنِّي أَصْبَحْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيعَ خَلْقِكَ أَنَّكَ أَنْتَ اللَّهُ لَا إِلَهَ إِلَّا أَنْتَ',
      transliteration: "Allahumma inni asbahtu ushhiduka wa ushhidu hamalata 'arshika wa mala'ikataka wa jami'a khalqika annaka antallahu la ilaha illa ant",
      translation: "O Allah, I call You, the bearers of Your Throne, Your angels, and all Your creation to witness that You are Allah; there is no deity except You.",
      reference: 'Abu Dawud 5069; Tirmidhi 3501',
      count: 4,
    },
    {
      title: 'Pleasure with Allah',
      arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ نَبِيًّا',
      transliteration: "Raditu billahi rabban, wa bil-Islami dinan, wa bi-Muhammadin nabiyyan",
      translation: "I am pleased with Allah as my Lord, Islam as my religion, and Muhammad as my Prophet.",
      reference: 'Abu Dawud 5072; Tirmidhi 3389',
      count: 3,
    },
    {
      title: 'Seeking pardon and well-being',
      arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ',
      transliteration: "Allahumma inni as'alukal-'afwa wal-'afiyata fid-dunya wal-akhirah",
      translation: "O Allah, I ask You for pardon and well-being in this world and the Hereafter.",
      reference: 'Abu Dawud 5074; Ibn Majah 3871',
      count: 1,
    },
    {
      title: 'Reliance upon Allah',
      arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
      transliteration: "Hasbiyallahu la ilaha illa huwa, 'alayhi tawakkaltu wa huwa rabbul-'arshil-'azim",
      translation: "Allah is sufficient for me; there is no deity except Him. Upon Him I rely, and He is the Lord of the Mighty Throne.",
      reference: 'Abu Dawud 5081; Qur\'an 9:129',
      count: 7,
    },
    {
      title: 'Glorification and praise',
      arabic: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
      transliteration: "SubhanAllahi wa bihamdih",
      translation: "Glory be to Allah and praise be to Him.",
      reference: 'Sahih Muslim 2692',
      count: 100,
    },
    {
      title: 'Tahlil — morning',
      arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadeer",
      translation: "There is no deity except Allah alone, without partner. His is the dominion and His is all praise, and He has power over everything.",
      reference: 'Sahih al-Bukhari 3293; Sahih Muslim 2691',
      count: 100,
    },
    {
      title: 'The three Quls',
      arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ قُلْ أَعُوذُ بِرَبِّ النَّاسِ',
      transliteration: "Qul Huwallahu Ahad / Qul A'udhu biRabbil-Falaq / Qul A'udhu biRabbin-Nas",
      translation: "Recite Surah Al-Ikhlas, Al-Falaq and An-Nas.",
      reference: 'Abu Dawud 5082; Tirmidhi 3575',
      count: 3,
    },
    {
      title: 'Ayat al-Kursi',
      arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ',
      transliteration: "Allahu la ilaha illa huwa, al-hayyul-qayyum, la ta'khudhuhu sinatun wa la nawm, lahu ma fis-samawati wa ma fil-ardh...",
      translation: "Recite Ayat al-Kursi — Allah, there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep...",
      reference: "al-Nasa'i al-Kubra; Qur'an 2:255",
      count: 1,
    },
  ],

  evening: [
    {
      title: 'Opening of the evening',
      arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
      transliteration: "Amsayna wa amsal-mulku lillah, la ilaha illallahu wahdahu la shareeka lah",
      translation: "We have reached the evening and the dominion belongs to Allah. Praise is for Allah. There is no deity except Allah alone, without partner.",
      reference: 'Sahih Muslim 2723',
      count: 1,
    },
    {
      title: 'Evening remembrance',
      arabic: 'اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ',
      transliteration: "Allahumma bika amsayna wa bika asbahna, wa bika nahya wa bika namutu wa ilaykal-masir",
      translation: "O Allah, by You we enter the evening and by You we enter the morning; by You we live and by You we die, and to You is the return.",
      reference: 'Abu Dawud 5068; Tirmidhi 3391',
      count: 1,
    },
    {
      title: 'Witnessing Allah',
      arabic: 'اللَّهُمَّ إِنِّي أَمْسَيْتُ أُشْهِدُكَ وَأُشْهِدُ حَمَلَةَ عَرْشِكَ وَمَلَائِكَتَكَ وَجَمِيعَ خَلْقِكَ أَنَّكَ أَنْتَ اللَّهُ لَا إِلَهَ إِلَّا أَنْتَ',
      transliteration: "Allahumma inni amsaytu ushhiduka wa ushhidu hamalata 'arshika wa mala'ikataka wa jami'a khalqika annaka antallahu la ilaha illa ant",
      translation: "O Allah, I call You, the bearers of Your Throne, Your angels, and all Your creation to witness that You are Allah; there is no deity except You.",
      reference: 'Abu Dawud 5069; Tirmidhi 3501',
      count: 4,
    },
    {
      title: 'Pleasure with Allah',
      arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ نَبِيًّا',
      transliteration: "Raditu billahi rabban, wa bil-Islami dinan, wa bi-Muhammadin nabiyyan",
      translation: "I am pleased with Allah as my Lord, Islam as my religion, and Muhammad as my Prophet.",
      reference: 'Abu Dawud 5072; Tirmidhi 3389',
      count: 3,
    },
    {
      title: 'Seeking pardon and well-being',
      arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ',
      transliteration: "Allahumma inni as'alukal-'afwa wal-'afiyata fid-dunya wal-akhirah",
      translation: "O Allah, I ask You for pardon and well-being in this world and the Hereafter.",
      reference: 'Abu Dawud 5074; Ibn Majah 3871',
      count: 1,
    },
    {
      title: 'Reliance upon Allah',
      arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ، عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
      transliteration: "Hasbiyallahu la ilaha illa huwa, 'alayhi tawakkaltu wa huwa rabbul-'arshil-'azim",
      translation: "Allah is sufficient for me; there is no deity except Him. Upon Him I rely, and He is the Lord of the Mighty Throne.",
      reference: 'Abu Dawud 5081; Qur\'an 9:129',
      count: 7,
    },
    {
      title: 'Glorification and praise',
      arabic: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
      transliteration: "SubhanAllahi wa bihamdih",
      translation: "Glory be to Allah and praise be to Him.",
      reference: 'Sahih Muslim 2692',
      count: 100,
    },
    {
      title: 'Tahlil — evening',
      arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadeer",
      translation: "There is no deity except Allah alone, without partner. His is the dominion and His is all praise, and He has power over everything.",
      reference: 'Sahih al-Bukhari 3293; Sahih Muslim 2691',
      count: 100,
    },
    {
      title: 'The three Quls',
      arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ ۝ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ۝ قُلْ أَعُوذُ بِرَبِّ النَّاسِ',
      transliteration: "Qul Huwallahu Ahad / Qul A'udhu biRabbil-Falaq / Qul A'udhu biRabbin-Nas",
      translation: "Recite Surah Al-Ikhlas, Al-Falaq and An-Nas.",
      reference: 'Abu Dawud 5082; Tirmidhi 3575',
      count: 3,
    },
    {
      title: 'Ayat al-Kursi',
      arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ',
      transliteration: "Allahu la ilaha illa huwa, al-hayyul-qayyum, la ta'khudhuhu sinatun wa la nawm, lahu ma fis-samawati wa ma fil-ardh...",
      translation: "Recite Ayat al-Kursi — Allah, there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep...",
      reference: "al-Nasa'i al-Kubra; Qur'an 2:255",
      count: 1,
    },
  ],

  'after-salah': [
    {
      title: 'Seeking forgiveness after prayer',
      arabic: 'أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، أَسْتَغْفِرُ اللَّهَ، اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالإِكْرَامِ',
      transliteration: "Astaghfirullah (x3). Allahumma antas-salam wa minkas-salam, tabarakta ya dhal-jalali wal-ikram",
      translation: "I seek Allah's forgiveness three times. O Allah, You are Peace and from You is peace. Blessed are You, O Possessor of Majesty and Honor.",
      reference: 'Sahih Muslim 591',
      count: 3,
    },
    {
      title: 'Tahlil after prayer',
      arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamdu, wa huwa 'ala kulli shay'in qadeer",
      translation: "There is no deity worthy of worship except Allah alone, without partner. To Him belongs the dominion and all praise, and He has power over everything.",
      reference: 'Sahih Muslim 597a',
      count: 1,
    },
    {
      title: 'Remembrance, gratitude, and worship',
      arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
      transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
      translation: "O Allah, help me to remember You, thank You, and worship You in the best manner.",
      reference: 'Abu Dawud 1522; al-Nasa\'i',
      count: 1,
    },
    {
      title: 'Acknowledging Allah\'s sole authority',
      arabic: 'اللَّهُمَّ لَا مَانِعَ لِمَا أَعْطَيْتَ، وَلَا مُعْطِيَ لِمَا مَنَعْتَ، وَلَا يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ',
      transliteration: "Allahumma la mani'a lima a'tayt, wa la mu'tiya lima mana't, wa la yanfa'u dhal-jaddi minkal-jadd",
      translation: "O Allah, none can withhold what You give, and none can give what You withhold.",
      reference: 'Bukhari & Muslim',
      count: 1,
    },
    {
      title: 'Seeking refuge from four evils',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْجُبْنِ، وَأَعُوذُ بِكَ مِنَ الْبُخْلِ، وَأَعُوذُ بِكَ مِنْ أَرْذَلِ الْعُمُرِ، وَأَعُوذُ بِكَ مِنْ فِتْنَةِ الدُّنْيَا وَعَذَابِ الْقَبْرِ',
      transliteration: "Allahumma inni a'udhu bika minal-jubn, wa a'udhu bika minal-bukhl, wa a'udhu bika min ardhali'l-'umr, wa a'udhu bika min fitnatid-dunya wa 'adhabil-qabr",
      translation: "O Allah, I seek refuge in You from cowardice, miserliness, decrepit old age, the trials of this world, and the punishment of the grave.",
      reference: 'Tirmidhi 3567',
      count: 1,
    },
    {
      title: 'SubhanAllah',
      arabic: 'سُبْحَانَ اللهِ',
      transliteration: "SubhanAllah",
      translation: "Glory be to Allah.",
      reference: 'Sahih Muslim 597a',
      count: 33,
    },
    {
      title: 'Alhamdulillah',
      arabic: 'الْحَمْدُ لِلَّهِ',
      transliteration: "Alhamdulillah",
      translation: "All praise belongs to Allah.",
      reference: 'Sahih Muslim 597a',
      count: 33,
    },
    {
      title: 'Allahu Akbar',
      arabic: 'اللَّهُ أَكْبَرُ',
      transliteration: "Allahu Akbar",
      translation: "Allah is the Greatest.",
      reference: 'Sahih Muslim 597a',
      count: 33,
    },
    {
      title: 'No power except with Allah',
      arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
      transliteration: "La hawla wa la quwwata illa billah",
      translation: "There is no power and no strength except through Allah.",
      reference: 'Reported in post-Salah adhkar',
      count: 1,
    },
    {
      title: 'Ayat al-Kursi',
      arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ',
      transliteration: "Allahu la ilaha illa huwa, al-hayyul-qayyum, la ta'khudhuhu sinatun wa la nawm...",
      translation: "Recite Ayat al-Kursi after every prayer.",
      reference: "al-Nasa'i; authenticated by Ibn Hibban",
      count: 1,
    },
  ],

  protection: [
    {
      title: 'Protection from all creation',
      arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
      transliteration: "A'udhu bikalimati'llahit-tammati min sharri ma khalaq",
      translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
      reference: 'Sahih Muslim 2708',
      count: 3,
    },
    {
      title: 'Protection from one\'s own senses',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ سَمْعِي، وَمِنْ شَرِّ بَصَرِي، وَمِنْ شَرِّ لِسَانِي، وَمِنْ شَرِّ قَلْبِي، وَمِنْ شَرِّ مَنِيِّي',
      transliteration: "Allahumma inni a'udhu bika min sharri sam'i, wa min sharri basari, wa min sharri lisani, wa min sharri qalbi, wa min sharri maniyyi",
      translation: "O Allah, I seek refuge in You from the evil of my hearing, sight, tongue, heart, and private desires.",
      reference: 'Tirmidhi 3492',
      count: 1,
    },
    {
      title: 'Protection from major trials',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ جَهَنَّمَ، وَمِنْ عَذَابِ الْقَبْرِ، وَمِنْ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ، وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ',
      transliteration: "Allahumma inni a'udhu bika min 'adhabi jahannam, wa min 'adhabil-qabr, wa min fitnatil-masihid-dajjal, wa min fitnatil-mahya wal-mamat",
      translation: "O Allah, I seek refuge in You from the punishment of Hell, the punishment of the grave, the trial of the false Messiah, and the trials of life and death.",
      reference: 'Tirmidhi 3494',
      count: 1,
    },
    {
      title: 'Protection from anxiety and weakness',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
      transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazan, wal-'ajzi wal-kasal, wal-bukhli wal-jubn, wa dhala'id-dayni wa ghalabatir-rijal",
      translation: "O Allah, I seek refuge in You from anxiety, grief, weakness, laziness, miserliness, overwhelming debt, and being overpowered by people.",
      reference: 'Tirmidhi 3484',
      count: 1,
    },
    {
      title: 'Protection from Dajjal and punishment',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكَسَلِ وَالْهَرَمِ، وَالْجُبْنِ وَالْبُخْلِ، وَفِتْنَةِ الْمَسِيحِ وَعَذَابِ الْقَبْرِ',
      transliteration: "Allahumma inni a'udhu bika minal-kasal wal-haram, wal-jubn wal-bukhl, wa fitnatil-masih wa 'adhabil-qabr",
      translation: "O Allah, I seek refuge in You from laziness, senility, cowardice, miserliness, the trial of the false Messiah, and the punishment of the grave.",
      reference: 'Tirmidhi 3485',
      count: 1,
    },
    {
      title: 'Protection from a heedless heart',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ قَلْبٍ لَا يَخْشَعُ، وَدُعَاءٍ لَا يُسْمَعُ، وَمِنْ نَفْسٍ لَا تَشْبَعُ، وَمِنْ عِلْمٍ لَا يَنْفَعُ',
      transliteration: "Allahumma inni a'udhu bika min qalbin la yakhsha', wa du'a'in la yusma', wa min nafsin la tashba', wa min 'ilmin la yanfa'",
      translation: "O Allah, I seek refuge in You from a heart that does not humble itself, a supplication that is not heard, a soul that is never satisfied, and knowledge that does not benefit.",
      reference: 'Tirmidhi 3482',
      count: 1,
    },
    {
      title: 'Protection from evil character',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ مُنْكَرَاتِ الْأَخْلَاقِ وَالْأَعْمَالِ وَالْأَهْوَاءِ',
      transliteration: "Allahumma inni a'udhu bika min munkaratil-akhlaq wal-a'mal wal-ahwa'",
      translation: "O Allah, I seek refuge in You from evil character, evil deeds, and evil desires.",
      reference: 'Tirmidhi 3591',
      count: 1,
    },
    {
      title: 'Protection from Satan',
      arabic: 'اللَّهُمَّ فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ، عَالِمَ الْغَيْبِ وَالشَّهَادَةِ، رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ، أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ',
      transliteration: "Allahumma fatirassamawati wal-ardh, 'alimal-ghaybi wash-shahadah, rabba kulli shay'in wa malikah, a'udhu bika min sharri nafsi wa min sharrish-shaytani wa shirkuh",
      translation: "O Allah, Creator of the heavens and earth, Knower of the unseen and seen, Lord and Owner of everything, I seek refuge in You from the evil of myself and from the evil and traps of Satan.",
      reference: 'Tirmidhi 3529',
      count: 1,
    },
    {
      title: 'Purification of the soul',
      arabic: 'اللَّهُمَّ آتِ نَفْسِي تَقْوَاهَا، وَزَكِّهَا أَنْتَ خَيْرُ مَنْ زَكَّاهَا، أَنْتَ وَلِيُّهَا وَمَوْلَاهَا',
      transliteration: "Allahumma ati nafsi taqwaha, wa zakkiha anta khayru man zakkaha, anta waliyyuha wa mawlaha",
      translation: "O Allah, grant my soul its piety and purify it; You are the best to purify it. You are its Guardian and Master.",
      reference: 'Sahih Muslim',
      count: 1,
    },
    {
      title: 'Seeking refuge from incapacity',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ وَالْهَرَمِ وَالْجُبْنِ وَالْبُخْلِ وَعَذَابِ الْقَبْرِ',
      transliteration: "Allahumma inni a'udhu bika minal-'ajzi wal-kasal wal-haram wal-jubn wal-bukhl wa 'adhabil-qabr",
      translation: "O Allah, I seek refuge in You from incapacity, laziness, cowardice, old age, miserliness, and the punishment of the grave.",
      reference: 'Sahih Muslim',
      count: 1,
    },
  ],

  forgiveness: [
    {
      title: 'Sayyid al-Istighfar',
      arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
      transliteration: "Allahumma anta rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastatatu, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayya, wa abu'u laka bidhanibi faghfir li, fa innahu la yaghfirudh-dhunuba illa ant",
      translation: "O Allah, You are my Lord. There is no deity except You. You created me and I am Your servant. I acknowledge Your blessings and my sins, so forgive me, for none forgives sins except You.",
      reference: 'Sahih al-Bukhari 6306',
      count: 1,
    },
    {
      title: 'Seeking forgiveness for wronging oneself',
      arabic: 'اللَّهُمَّ إِنِّي ظَلَمْتُ نَفْسِي ظُلْمًا كَثِيرًا، وَلَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ، فَاغْفِرْ لِي مَغْفِرَةً مِنْ عِنْدِكَ وَارْحَمْنِي',
      transliteration: "Allahumma inni zalamtu nafsi zulman kathiran, wa la yaghfirudh-dhunuba illa ant, faghfir li maghfiratan min 'indik warhamni",
      translation: "O Allah, I have greatly wronged myself. None forgives sins except You, so forgive me with forgiveness from You and have mercy upon me.",
      reference: 'Bukhari 6326; Muslim 2705',
      count: 1,
    },
    {
      title: 'Seeking Allah\'s pardon',
      arabic: 'اللَّهُمَّ إِنَّكَ عَفُوٌّ كَرِيمٌ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',
      transliteration: "Allahumma innaka 'afuwwun karimun tuhibbul-'afwa fa'fu 'anni",
      translation: "O Allah, You are Pardoning and Generous; You love pardon, so pardon me.",
      reference: 'Tirmidhi 3513',
      count: 1,
    },
    {
      title: 'Glory and forgiveness',
      arabic: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، اللَّهُمَّ اغْفِرْ لِي',
      transliteration: "SubhanakalLahumma wa bihamdik, Allahummaghfir li",
      translation: "Glory be to You, O Allah, and praise is Yours. O Allah, forgive me.",
      reference: 'Sahih Muslim 484a; Bukhari 794',
      count: 1,
    },
    {
      title: 'Glorification and repentance',
      arabic: 'سُبْحَانَكَ وَبِحَمْدِكَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ',
      transliteration: "Subhanakal wa bihamdik, astaghfiruka wa atubu ilayk",
      translation: "Glory be to You and praise is Yours. I seek Your forgiveness and repent to You.",
      reference: 'Sahih Muslim 484b',
      count: 1,
    },
    {
      title: 'Complete istighfar',
      arabic: 'أَسْتَغْفِرُ اللَّهَ الْعَظِيمَ الَّذِي لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ',
      transliteration: "Astaghfirullaha'l-'azimalladhi la ilaha illa huwal-hayyal-qayyumu wa atubu ilayh",
      translation: "I seek forgiveness from Allah the Mighty, there is no deity except Him, the Ever-Living, the Sustainer, and I repent to Him.",
      reference: 'Abu Dawud; Tirmidhi',
      count: 1,
    },
    {
      title: 'Brief supplication for forgiveness',
      arabic: 'رَبِّ اغْفِرْ لِي',
      transliteration: "Rabbighfir li",
      translation: "My Lord, forgive me.",
      reference: 'Abu Dawud; authentic narration',
      count: 1,
    },
    {
      title: 'Comprehensive supplication',
      arabic: 'اللَّهُمَّ اغْفِرْ لِي وَارْحَمْنِي وَاهْدِنِي وَاجْبُرْنِي وَعَافِنِي وَارْزُقْنِي وَارْفَعْنِي',
      transliteration: "Allahummaghfir li warhamni wahdini wajburni wa 'afini warzuqni warfa'ni",
      translation: "O Allah, forgive me, have mercy on me, guide me, support me, grant me well-being, provide for me, and raise me.",
      reference: 'Abu Dawud; Ibn Majah; Tirmidhi',
      count: 1,
    },
    {
      title: 'Seeking forgiveness for ignorance',
      arabic: 'اللَّهُمَّ اغْفِرْ لِي خَطِيئَتِي وَجَهْلِي، وَإِسْرَافِي فِي أَمْرِي',
      transliteration: "Allahummaghfir li khati'ati wa jahli, wa israfi fi amri",
      translation: "O Allah, forgive my mistakes, my ignorance, and my excesses in my affairs.",
      reference: 'Bukhari & Muslim',
      count: 1,
    },
    {
      title: 'Forgiveness for all sins',
      arabic: 'اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ، وَعَلَانِيَتَهُ وَسِرَّهُ',
      transliteration: "Allahummaghfir li dhanbi kullahu, diqqahu wa jillahu, wa awwalahu wa akhirahu, wa 'alaniyyatahu wa sirrah",
      translation: "O Allah, forgive all my sins — the small and the great, the first and the last, the apparent and the hidden.",
      reference: 'Sahih Muslim 483',
      count: 1,
    },
  ],

  gratitude: [
    {
      title: 'Remembrance, gratitude, and worship',
      arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
      transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
      translation: "O Allah, help me to remember You, thank You, and worship You excellently.",
      reference: 'Abu Dawud 1522; al-Nasa\'i',
      count: 1,
    },
    {
      title: 'All praise belongs to Allah',
      arabic: 'الْحَمْدُ لِلَّهِ',
      transliteration: "Alhamdulillah",
      translation: "All praise belongs to Allah.",
      reference: 'Authentic Sunnah dhikr',
      count: 33,
    },
    {
      title: 'Praise of our Lord',
      arabic: 'رَبَّنَا وَلَكَ الْحَمْدُ',
      transliteration: "Rabbana wa lakal-hamd",
      translation: "Our Lord, to You belongs all praise.",
      reference: 'Sahih al-Bukhari 796',
      count: 1,
    },
    {
      title: 'O Allah, our Lord, all praise is Yours',
      arabic: 'اللَّهُمَّ رَبَّنَا لَكَ الْحَمْدُ',
      transliteration: "Allahumma rabbana lakal-hamd",
      translation: "O Allah, our Lord, to You belongs all praise.",
      reference: 'Bukhari; al-Nasa\'i',
      count: 1,
    },
    {
      title: 'Abundant and blessed praise',
      arabic: 'رَبَّنَا وَلَكَ الْحَمْدُ حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ',
      transliteration: "Rabbana wa lakal-hamdu hamdan kathiran tayyiban mubarakan fih",
      translation: "Our Lord, to You belongs abundant, pure and blessed praise.",
      reference: 'Sahih al-Bukhari',
      count: 1,
    },
    {
      title: 'Glory and praise combined',
      arabic: 'سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ',
      transliteration: "SubhanAllahi wal-hamdulillah",
      translation: "Glory be to Allah and all praise belongs to Allah.",
      reference: 'Authentic Sunnah dhikr',
      count: 33,
    },
    {
      title: 'Glory, praise and His attributes',
      arabic: 'سُبْحَانَ اللهِ وَبِحَمْدِهِ',
      transliteration: "SubhanAllahi wa bihamdih",
      translation: "Glory be to Allah and praise belongs to Him.",
      reference: 'Sahih al-Bukhari',
      count: 100,
    },
    {
      title: 'Praise and dominion',
      arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ',
      transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul-mulku wa lahul-hamd",
      translation: "There is no deity except Allah alone, without partner. His is the dominion and His is all praise.",
      reference: 'Sahih Muslim 597a',
      count: 1,
    },
    {
      title: 'Praise of the Sustainer',
      arabic: 'اللَّهُمَّ لَكَ الْحَمْدُ، أَنْتَ قَيِّمُ السَّمَاوَاتِ وَالْأَرْضِ وَمَنْ فِيهِنَّ',
      transliteration: "Allahumma lakal-hamd, anta qayyimus-samawati wal-ardhi wa man fihinn",
      translation: "O Allah, to You belongs all praise. You are the Sustainer of the heavens, the earth, and all within them.",
      reference: 'Sahih al-Bukhari 1120',
      count: 1,
    },
    {
      title: 'The three glorifications',
      arabic: 'سُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ وَاللَّهُ أَكْبَرُ',
      transliteration: "SubhanAllahi wal-hamdulillahi wallahu akbar",
      translation: "Glory be to Allah, all praise belongs to Allah, and Allah is the Greatest.",
      reference: 'Authentic Sunnah dhikr',
      count: 33,
    },
  ],

  'before-sleep': [
    {
      title: 'In Allah\'s name I sleep',
      arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
      transliteration: "Bismikallahuma amutu wa ahya",
      translation: "In Your name, O Allah, I die and I live.",
      reference: 'Sahih al-Bukhari 6312',
      count: 1,
    },
    {
      title: 'Complete submission before sleep',
      arabic: 'اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ',
      transliteration: "Allahumma aslamtu nafsi ilayk, wa wajjahtu wajhi ilayk, wa fawwadtu amri ilayk, wa alja'tu zahri ilayk, raghbatan wa rahbatan ilayk",
      translation: "O Allah, I submit myself to You, turn my face to You, entrust my affairs to You, and seek refuge with You, in hope and fear of You.",
      reference: 'Sahih al-Bukhari 6313',
      count: 1,
    },
    {
      title: 'Laying down the side',
      arabic: 'بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، إِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا',
      transliteration: "Bismika rabbi wada'tu janbi, wa bika arfa'uh, in amsakta nafsi farhamha, wa in arsaltaha fahfazha",
      translation: "In Your name, my Lord, I lay down my side, and by You I raise it. If You take my soul, have mercy on it; and if You return it, protect it.",
      reference: 'Sahih al-Bukhari 6320',
      count: 1,
    },
    {
      title: 'Seeking refuge in Allah from Himself',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِرِضَاكَ مِنْ سَخَطِكَ، وَبِمُعَافَاتِكَ مِنْ عُقُوبَتِكَ، وَأَعُوذُ بِكَ مِنْكَ',
      transliteration: "Allahumma inni a'udhu biridaka min sakhatik, wa bimu'afatika min 'uqubatik, wa a'udhu bika mink",
      translation: "O Allah, I seek refuge in Your pleasure from Your anger, in Your forgiveness from Your punishment, and in You from You.",
      reference: 'Sahih Muslim',
      count: 1,
    },
    {
      title: 'Forgiveness for all sins',
      arabic: 'اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ، وَعَلَانِيَتَهُ وَسِرَّهُ',
      transliteration: "Allahummaghfir li dhanbi kullahu, diqqahu wa jillahu, wa awwalahu wa akhirahu, wa 'alaniyyatahu wa sirrah",
      translation: "O Allah, forgive all my sins — the small and the great, the first and the last, the apparent and the hidden.",
      reference: 'Sahih Muslim 483',
      count: 1,
    },
    {
      title: 'Tasbeeh before sleep',
      arabic: 'اللَّهُ أَكْبَرُ ×٣٣، سُبْحَانَ اللهِ ×٣٣، الْحَمْدُ لِلَّهِ ×٣٣',
      transliteration: "Allahu Akbar ×33, SubhanAllah ×33, Alhamdulillah ×33",
      translation: "Allah is the Greatest 33 times, Glory be to Allah 33 times, and praise be to Allah 33 times.",
      reference: 'Sahih al-Bukhari 6318',
      count: 1,
    },
    {
      title: 'Surah Al-Ikhlas',
      arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ',
      transliteration: "Qul Huwallahu Ahad",
      translation: "Recite Surah Al-Ikhlas.",
      reference: 'Sahih al-Bukhari 6319',
      count: 3,
    },
    {
      title: 'Surah Al-Falaq',
      arabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ',
      transliteration: "Qul A'udhu biRabbil-Falaq",
      translation: "Recite Surah Al-Falaq.",
      reference: 'Sahih al-Bukhari 6319',
      count: 3,
    },
    {
      title: 'Surah An-Nas',
      arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ',
      transliteration: "Qul A'udhu biRabbin-Nas",
      translation: "Recite Surah An-Nas.",
      reference: 'Sahih al-Bukhari 6319',
      count: 3,
    },
    {
      title: 'Last two verses of Al-Baqarah',
      arabic: 'آخِرَ آيَتَيْنِ مِنْ سُورَةِ الْبَقَرَةِ',
      transliteration: "Akhira ayatayni min Suratul-Baqarah",
      translation: "Recite the last two verses of Surah Al-Baqarah.",
      reference: 'Sahih al-Bukhari 5009',
      count: 1,
    },
  ],

  travel: [
    {
      title: 'Dua upon mounting a vehicle',
      arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ',
      transliteration: "SubhanalLadhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila rabbina lamunqalibun",
      translation: "Glory be to Him who subjected this to us, though we could not have controlled it ourselves; and surely to our Lord we will return.",
      reference: 'Tirmidhi 3447',
      count: 1,
    },
    {
      title: 'Asking for righteousness in travel',
      arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ فِي سَفَرِي هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى',
      transliteration: "Allahumma inni as'aluka fi safari hadhal-birra wat-taqwa, wa minal-'amali ma tarda",
      translation: "O Allah, I ask You in this journey for righteousness, piety, and deeds that please You.",
      reference: 'Tirmidhi 3447',
      count: 1,
    },
    {
      title: 'Ease of journey',
      arabic: 'اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَذَا وَاطْوِ عَنَّا بُعْدَهُ',
      transliteration: "Allahumma hawwin 'alayna safarana hadha watwi 'anna bu'dah",
      translation: "O Allah, make this journey easy for us and shorten its distance for us.",
      reference: 'Tirmidhi 3447',
      count: 1,
    },
    {
      title: 'Companion in travel',
      arabic: 'اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ وَالْخَلِيفَةُ فِي الْأَهْلِ',
      transliteration: "Allahumma antassahibu fis-safari wal-khalifatu fil-ahl",
      translation: "O Allah, You are our Companion during the journey and the Guardian of our family.",
      reference: 'Tirmidhi 3438/3439',
      count: 1,
    },
    {
      title: 'Protection from hardships of travel',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ وَعْثَاءِ السَّفَرِ وَكَآبَةِ الْمُنْقَلَبِ',
      transliteration: "Allahumma inni a'udhu bika min wa'tha'is-safari wa ka'abatil-munqalab",
      translation: "O Allah, I seek refuge in You from the hardships of travel and the sadness of returning.",
      reference: 'Tirmidhi 3438/3439',
      count: 1,
    },
    {
      title: 'Asking Allah to accompany and guard',
      arabic: 'اللَّهُمَّ أَصْحِبْنَا فِي سَفَرِنَا وَاخْلُفْنَا فِي أَهْلِنَا',
      transliteration: "Allahumma ashibna fi safarana wakhlifna fi ahlina",
      translation: "O Allah, accompany us on our journey and take care of our family in our absence.",
      reference: 'Tirmidhi 3439',
      count: 1,
    },
    {
      title: 'Protection from decline after progress',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْحَوْرِ بَعْدَ الْكَوْنِ',
      transliteration: "Allahumma inni a'udhu bika minal-hawri ba'dal-kawn",
      translation: "O Allah, I seek refuge in You from decline after progress.",
      reference: 'Tirmidhi 3439',
      count: 1,
    },
    {
      title: 'Protection from supplication of the oppressed',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ دَعْوَةِ الْمَظْلُومِ',
      transliteration: "Allahumma inni a'udhu bika min da'watil-mazlum",
      translation: "O Allah, I seek refuge in You from the supplication of the oppressed.",
      reference: 'Tirmidhi 3439',
      count: 1,
    },
    {
      title: 'Protection for family and wealth',
      arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ سُوءِ الْمَنْظَرِ فِي الْأَهْلِ وَالْمَالِ',
      transliteration: "Allahumma inni a'udhu bika min su'il-manzari fil-ahli wal-mal",
      translation: "O Allah, I seek refuge in You from seeing harm befall my family or wealth.",
      reference: 'Tirmidhi 3439 / Ibn Majah 3888',
      count: 1,
    },
    {
      title: 'Returning from travel',
      arabic: 'آيِبُونَ، تَائِبُونَ، عَابِدُونَ، لِرَبِّنَا حَامِدُونَ',
      transliteration: "Ayibun, ta'ibun, 'abidun, lirabbina hamidun",
      translation: "We return safely, repentant, worshipping our Lord, and praising Him.",
      reference: 'Sahih Muslim',
      count: 1,
    },
  ],
};
